server1/config/routes.rb
Rails.application.routes.draw do
  resources :wines, :defaults => { :format => 'json' }

end

server1/app/models/users.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, 
                  :temp_password

  validates :email, :first_name, :last_name, :presence =>true
  validates_uniqueness_of :email

end

server1/app/models/wine.rb
class Wine < ActiveRecord::Base
end

server1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

server1/app/controllers/users_controller.rb
class Api::UsersController < ApplicationController
  http_basic_authenticate_with :name => "myfinance", :password => "credit123"

  skip_before_filter :authenticate_user! # we do not need devise authentication here
  before_filter :fetch_user, :except => [:index, :create]

 def fetch_user
    @user = User.find_by_id(params[:id])
  end

  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @user }
      format.xml { render xml: @user }
    end
  end

  def create
    @user = User.new(params[:user])
    @user.temp_password = Devise.friendly_token
    respond_to do |format|
      if @user.save
        format.json { render json: @user, status: :created }
        format.xml { render xml: @user, status: :created }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

server1/app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

 def fetch_wines
    @wines = Wine.find_by_id(params[:title])
  end

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
      respond_to do |format|
      format.json { render json: @wines }
      format.xml { render xml: @wines}
  end
end
  # GET /wines/1
  # GET /wines/1.json
  def show
    respond_to do |format|
      format.json { render json: @wines }
      format.xml { render xml: @wines }
  end
end
  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  
end

server1/app/helpers/application_helper.rb
module ApplicationHelper
end

server1/app/helpers/wines_helper.rb
module WinesHelper
end

server1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Server1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

server1/app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Img_url %><br>
    <%= f.text_field :Img_url %>
  </div>
  <div class="field">
    <%= f.label :Origin %><br>
    <%= f.text_field :Origin %>
  </div>
  <div class="field">
    <%= f.label :Type %><br>
    <%= f.text_field :Type %>
  </div>
  <div class="field">
    <%= f.label :Size %><br>
    <%= f.text_field :Size %>
  </div>
  <div class="field">
    <%= f.label :Price %><br>
    <%= f.text_field :Price %>
  </div>
  <div class="field">
    <%= f.label :Company %><br>
    <%= f.text_field :Company %>
  </div>
  <div class="field">
    <%= f.label :Suit_veg %><br>
    <%= f.text_field :Suit_veg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server1/app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

server1/app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wines</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Img url</th>
      <th>Origin</th>
      <th>Type</th>
      <th>Size</th>
      <th>Price</th>
      <th>Company</th>
      <th>Suit veg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.Title %></td>
        <td><%= wine.Description %></td>
        <td><%= wine.Img_url %></td>
        <td><%= wine.Origin %></td>
        <td><%= wine.Type %></td>
        <td><%= wine.Size %></td>
        <td><%= wine.Price %></td>
        <td><%= wine.Company %></td>
        <td><%= wine.Suit_veg %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

server1/app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

server1/app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wine.Title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wine.Description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @wine.Img_url %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @wine.Origin %>
</p>

<p>
  <strong>Type:</strong>
  <%= @wine.Type %>
</p>

<p>
  <strong>Size:</strong>
  <%= @wine.Size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wine.Price %>
</p>

<p>
  <strong>Company:</strong>
  <%= @wine.Company %>
</p>

<p>
  <strong>Suit veg:</strong>
  <%= @wine.Suit_veg %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>